#This file as Config struct

title="数据库配置"

#This block as DBName struct
[dbName]
StockMarketRawD1 = "StockMarketRawD1"		# 股票行情原始数据，周期为1日
StockD1 = "StockD1" 						# 证券行情（后复权）及指标数据，周期为1日
StockW1 = "StockW1"						# 证券行情（后复权）及指标数据，周期为1个星期
StockM1 = "StockM1"						# 证券行情（后复权）及指标数据，周期为1个月
StockQ1 = "StockQ1"						# 证券行情（后复权）及指标数据，周期为1个季度
StockY1 = "StockY1"						# 证券行情（后复权）及指标数据，周期为1个年
IndexMarketRawD1 = "IndexMarketRawD1" 	# 指数行情原始数据，周期为1日
IndexD1 = "IndexD1"						# 指数行情原始数据，周期为1日
IndexW1 = "IndexW1"						# 指数行情原始数据，周期为1星期
IndexM1 = "IndexM1"						# 指数行情原始数据，周期为1个月
IndexQ1 = "IndexQ1"						# 指数行情原始数据，周期为1个季度
IndexY1 = "IndexY1"						# 指数行情原始数据，周期为1个年
Analysis = "Analysis"					# 分析系统数据库
System = "System"						# 系统库，用于存储系统状态信息
